name: thousand
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_core:
  firebase_auth:
  datetime_picker_formfield:
  firebase_storage: ^5.0.1
  image_cropper: ^1.3.1
  image_picker:
  flutter_svg_provider: ^0.1.8 # to use svg images
  google_fonts: ^1.1.2 # to import google fonts and text theme
  provider:
  form_field_validator:
  hexcolor:
  flutter_spinkit:
  flutter_rounded_date_picker:
  font_awesome_flutter:
  flutter_local_notifications: ^3.0.1+6
  shared_preferences:
  cached_network_image:
  firebase_messaging: ^7.0.3
  flutter_widgets:
  photo_view:
  url_launcher:
  fluttertoast:
  random_color:
  page_transition:
  flutter_share:
  flutter_staggered_grid_view:
  transparent_image:
  simple_animations:
  flutter_launcher_icons: "^0.7.3"
  photo:
  http:
  esys_flutter_share:
  flare_flutter: ^2.0.6
  flutter_app_badger: ^1.1.2
  carousel_slider: ^1.4.1
  badges: ^1.1.4
  flutter_screenutil: ^3.2.0
  lottie: ^0.7.0+1
  status_alert: ^0.1.3
  linkable: ^1.0.4
  flappy_search_bar: ^1.7.2
  flutter_search_bar: ^2.1.0
  giphy_picker:
  flutter_audio_recorder: ^0.5.5
  screenshot: ^0.2.0
  share: ^0.6.5+4
  swipe_to: 0.0.1+8
  camera: ^0.6.4+5
  video_thumbnail:
  thumbnails: ^1.0.1
  storage_path: ^0.2.0
  photo_manager:
  media_picker_builder: ^1.3.2
  giphy_get:
  text_editor: ^0.3.2
  cupertino_icons: ^1.0.0
  flutter_svg:
  emoji_picker: ^0.1.0
  path_provider: ^1.6.22
  path:
  video_player: ^1.0.1
  socket_io_client: ^0.9.12
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: dance
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: FjallaOne
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: MonteCarlo
      fonts:
        - asset: assets/fonts/MonteCarlo-Regular.ttf
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: PaletteMosaic
      fonts:
        - asset: assets/fonts/PaletteMosaic-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
    - family: Robotomedium
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: Robotoregular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
